### ISSUE TITLE
NullReferenceException when JWT has no grant_type claim

### ISSUE THREAD

**Issue by sam-garland** [SAP/cloud-security-services-integration-library#1261]
**Issue Summary**
- An exception is thrown at the following line of code when invoked for a JWT that has no `grant_type` claim:
https://github.com/SAP/cloud-security-services-integration-library/blob/46ee39468739008880a1af1d4698750a64c36a21/java-security/src/main/java/com/sap/cloud/security/token/XsuaaToken.java#L112

I am seeing such a JWT being produced by XSUAA when making call from a workflow service task to an API using a destination that has the authentication type of `OAuth2UserTokenExchange`.

The fact that the XSUAA is not adding a `grant_type` claim in this case is inconsistent, but I don't think such a JWT is invalid. 

Here is a stack trace produced in an undertow based application when such a JWT is received:

```
Cannot invoke "com.sap.cloud.security.token.GrantType.ordinal()" because the return value of "com.sap.cloud.security.token.XsuaaToken.getGrantType()" is null
at com.sap.cloud.security.token.XsuaaToken.getPrincipal(XsuaaToken.java:110)
at com.sap.cloud.platform.visualization.services.security.JWTAccount.<init>(JWTAccount.java:40)
at com.sap.cloud.platform.visualization.services.security.JWTBearerTokenAuthenticationMechanism.getAccount(JWTBearerTokenAuthenticationMechanism.java:122)
at com.sap.cloud.platform.visualization.services.security.JWTBearerTokenAuthenticationMechanism.authenticate(JWTBearerTokenAuthenticationMechanism.java:83)
at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:245)
at io.undertow.security.impl.SecurityContextImpl.attemptAuthentication(SecurityContextImpl.java:125)
at io.undertow.security.impl.SecurityContextImpl.authTransition(SecurityContextImpl.java:99)
at io.undertow.security.impl.SecurityContextImpl.authenticate(SecurityContextImpl.java:92)
at io.undertow.security.handlers.AuthenticationCallHandler.handleRequest(AuthenticationCallHandler.java:50)
at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
at com.sap.cloud.platform.visualization.services.handlers.JWTHandler.handleRequestInternal(JWTHandler.java:109)
at com.sap.cloud.platform.visualization.services.handlers.CorrelationIdHandler.handleRequest(CorrelationIdHandler.java:25)
at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
at io.undertow.server.handlers.ExceptionHandler.handleRequest(ExceptionHandler.java:29)
at io.undertow.server.handlers.BlockingHandler.handleRequest(BlockingHandler.java:56)
at com.sap.cloud.platform.visualization.services.handlers.CORSResponseHandler.handleRequestInternal(CORSResponseHandler.java:216)
at com.sap.cloud.platform.visualization.services.handlers.CorrelationIdHandler.handleRequest(CorrelationIdHandler.java:25)
at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
at java.base/java.lang.Thread.run(Thread.java:833)
```

Please add a null check before the switch statement.

I would expect a `grant_type` of `user_token` to be added to such a JWT by the XSUAA, but in any case, the code in this library should not throw an exception here regardless of whether this inconsistent behaviour is resolved in the XSUAA.

**Comment by liga-oz** [comment]
@sam-garland thanks for reporting this bug, it will be fixed in the next version release 👍🏻
