### ISSUE TITLE
Circular reference when declaring MyCustomTokenAuthConverter as suggested

### ISSUE THREAD

**Issue by clnative** [SAP/cloud-security-services-integration-library#1277]
It remains unclear, how the suggestion at

https://github.com/SAP/cloud-security-services-integration-library/blob/2ceaf87fc709cd4ce09d94823efaf886a1ffa5e5/spring-security/README.md?plain=1#L126

should work. If doing so, I always end up in a 

```
Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'myCustomTokenAuthConverter': Requested bean is currently in creation: Is there an unresolvable circular reference?
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.beforeSingletonCreation(DefaultSingletonBeanRegistry.java:355)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:227)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
```

**Comment by clnative** [comment]
I think your trick at https://github.com/SAP/cloud-security-services-integration-library/blob/0f2952a97506e850da23fc1b6acd2a6e07d414c1/samples/spring-security-hybrid-usage/src/main/java/sample/spring/security/SecurityConfiguration.java is that you have it defined as inner static class. My one is "a little bigger one" and resides in an own class file. However, with that one, the autowired declaration becomes cyclic.
Essentially, my current workaround is that I directly refer to `com.sap.cloud.security.spring.token.authentication.XsuaaTokenAuthorizationConverter`. However I doubt that this approach is intentional.

I think it would be worthwhile to mention in the guide that you should declare the converter as inner class (or you will face the problem as above).

**Comment by liga-oz** [comment]
Doesn't seem to be the case
https://github.com/SAP/cloud-security-services-integration-library/blob/GH-1277/samples/spring-security-hybrid-usage/src/main/java/sample/spring/security/HybridConverter.java 

It is possible to define the converter in its own class.

**Comment by liga-oz** [comment]
Closing due to inactivity
