### ISSUE TITLE
Applying patch 2.17.2 - error java.lang.ClassNotFoundException: com.sap.cloud.security.token.validation.XsuaaJkuFactory

### ISSUE THREAD

**Issue by giselebrito** [SAP/cloud-security-services-integration-library#1398]
**Question Summary**
We are upgrading several of our applications using SAP Cloud Security libraries to the latest 2.17.2 to mitigate the vulnerability identified recently.
However, when we change to the latest 2.x version, our application fails to start due to an error java.lang.ClassNotFoundException: com.sap.cloud.security.token.validation.XsuaaJkuFactory
We are not sure how to proceed as we don't find any configuration / documentation related to the factory class in the usage sample apps.

- *Client library* we are using: resourceserver-security-spring-boot-starter and java-security-test
upgraded from 2.13.9 to 2.17.2 
- *Environment*: Cloud Foundry
- *Additional information*: at this time, we are unable to upgrade to 3.x security libraries as it requires a significant code upgrade

Could you please advise on any additional configuration we need to do?

Complete stack trace:

```
023-12-14 15:07:14.938 ERROR 29107 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Unsatisfied dependency expressed through method 'setFilterChains' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'filterChain' defined in class path resource [com/sap/prm/partnerpayment/core/configuration/XsuaaSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.web.SecurityFilterChain]: Factory method 'filterChain' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hybridJwtDecoder' defined in class path resource [com/sap/cloud/security/spring/autoconfig/HybridIdentityServicesAutoConfiguration$JwtDecoderConfigurations.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.jwt.JwtDecoder]: Factory method 'hybridJwtDecoder' threw exception; nested exception is java.lang.NoClassDefFoundError: com/sap/cloud/security/token/validation/XsuaaJkuFactory
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(AutowiredAnnotationBeanPostProcessor.java:768)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:720)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
        at com.sap.prm.partnerpayment.PartnerPaymentFormApiApplication.main(PartnerPaymentFormApiApplication.java:14)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'filterChain' defined in class path resource [com/sap/prm/partnerpayment/core/configuration/XsuaaSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.web.SecurityFilterChain]: Factory method 'filterChain' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hybridJwtDecoder' defined in class path resource [com/sap/cloud/security/spring/autoconfig/HybridIdentityServicesAutoConfiguration$JwtDecoderConfigurations.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.jwt.JwtDecoder]: Factory method 'hybridJwtDecoder' threw exception; nested exception is java.lang.NoClassDefFoundError: com/sap/cloud/security/token/validation/XsuaaJkuFactory
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1609)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1573)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1462)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1349)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(AutowiredAnnotationBeanPostProcessor.java:760)
        ... 25 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.web.SecurityFilterChain]: Factory method 'filterChain' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hybridJwtDecoder' defined in class path resource [com/sap/cloud/security/spring/autoconfig/HybridIdentityServicesAutoConfiguration$JwtDecoderConfigurations.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.jwt.JwtDecoder]: Factory method 'hybridJwtDecoder' threw exception; nested exception is java.lang.NoClassDefFoundError: com/sap/cloud/security/token/validation/XsuaaJkuFactory
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 41 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hybridJwtDecoder' defined in class path resource [com/sap/cloud/security/spring/autoconfig/HybridIdentityServicesAutoConfiguration$JwtDecoderConfigurations.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.jwt.JwtDecoder]: Factory method 'hybridJwtDecoder' threw exception; nested exception is java.lang.NoClassDefFoundError: com/sap/cloud/security/token/validation/XsuaaJkuFactory
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:233)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1284)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1245)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:494)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1174)
        at org.springframework.security.config.annotation.web.configurers.oauth2.server.resource.OAuth2ResourceServerConfigurer$JwtConfigurer.getJwtDecoder(OAuth2ResourceServerConfigurer.java:419)
        at org.springframework.security.config.annotation.web.configurers.oauth2.server.resource.OAuth2ResourceServerConfigurer$JwtConfigurer.getAuthenticationProvider(OAuth2ResourceServerConfigurer.java:428)
        at org.springframework.security.config.annotation.web.configurers.oauth2.server.resource.OAuth2ResourceServerConfigurer.getAuthenticationProvider(OAuth2ResourceServerConfigurer.java:335)
        at org.springframework.security.config.annotation.web.configurers.oauth2.server.resource.OAuth2ResourceServerConfigurer.init(OAuth2ResourceServerConfigurer.java:254)
        at org.springframework.security.config.annotation.web.configurers.oauth2.server.resource.OAuth2ResourceServerConfigurer.init(OAuth2ResourceServerConfigurer.java:147)
        at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.init(AbstractConfiguredSecurityBuilder.java:338)
        at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:300)
        at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:38)
        at com.sap.prm.partnerpayment.core.configuration.XsuaaSecurityConfiguration.filterChain(XsuaaSecurityConfiguration.java:54)
        at com.sap.prm.partnerpayment.core.configuration.XsuaaSecurityConfiguration$$EnhancerBySpringCGLIB$$b294b0aa.CGLIB$filterChain$0(<generated>)
        at com.sap.prm.partnerpayment.core.configuration.XsuaaSecurityConfiguration$$EnhancerBySpringCGLIB$$b294b0aa$$FastClassBySpringCGLIB$$73540c23.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at com.sap.prm.partnerpayment.core.configuration.XsuaaSecurityConfiguration$$EnhancerBySpringCGLIB$$b294b0aa.filterChain(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 42 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.jwt.JwtDecoder]: Factory method 'hybridJwtDecoder' threw exception; nested exception is java.lang.NoClassDefFoundError: com/sap/cloud/security/token/validation/XsuaaJkuFactory
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 76 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/sap/cloud/security/token/validation/XsuaaJkuFactory
        at com.sap.cloud.security.token.validation.validators.XsuaaJwtSignatureValidator$1.<init>(XsuaaJwtSignatureValidator.java:36)
        at com.sap.cloud.security.token.validation.validators.XsuaaJwtSignatureValidator.<init>(XsuaaJwtSignatureValidator.java:33)
        at com.sap.cloud.security.token.validation.validators.JwtValidatorBuilder.createDefaultValidators(JwtValidatorBuilder.java:221)
        at com.sap.cloud.security.token.validation.validators.JwtValidatorBuilder.build(JwtValidatorBuilder.java:205)
        at com.sap.cloud.security.spring.token.authentication.JwtDecoderBuilder.build(JwtDecoderBuilder.java:132)
        at com.sap.cloud.security.spring.autoconfig.HybridIdentityServicesAutoConfiguration$JwtDecoderConfigurations.hybridJwtDecoder(HybridIdentityServicesAutoConfiguration.java:74)
        at com.sap.cloud.security.spring.autoconfig.HybridIdentityServicesAutoConfiguration$JwtDecoderConfigurations$$EnhancerBySpringCGLIB$$5f474462.CGLIB$hybridJwtDecoder$0(<generated>)
        at com.sap.cloud.security.spring.autoconfig.HybridIdentityServicesAutoConfiguration$JwtDecoderConfigurations$$EnhancerBySpringCGLIB$$5f474462$$FastClassBySpringCGLIB$$25190062.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at com.sap.cloud.security.spring.autoconfig.HybridIdentityServicesAutoConfiguration$JwtDecoderConfigurations$$EnhancerBySpringCGLIB$$5f474462.hybridJwtDecoder(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 77 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.sap.cloud.security.token.validation.XsuaaJkuFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 93 common frames omitted
```

pom.xml

```
<dependency>
	<groupId>com.sap.cloud.security</groupId>
	<artifactId>resourceserver-security-spring-boot-starter</artifactId>
	<version>2.17.2</version>
</dependency>
<dependency>
	<groupId>com.sap.cloud.security</groupId>
	<artifactId>java-security-test</artifactId>
	<version>2.17.2</version>
	<scope>test</scope>
</dependency>
```

**Comment by nenaraab** [comment]
Dear @giselebrito 

We need to analyze your dependencies:

In order to analyze the dependencies
of your application, you can use the maven  [dependency plugin](http://maven.apache.org/plugins/maven-dependency-plugin/usage.html#dependency:tree).

It allows you to print the effective dependencies of your application. You can execute the plugin via the command line from
the directory where your `pom.xml` file is stored with `mvn dependency:tree`.
This will generate an output like this:

```log
❯ mvn dependency:tree
```

Furthermore, as sap_java_buildpack provides java-security (and java-api) do you leverage sap_java_buildpack and if yes, in which version?

Thanks a lot!
